### ISSUE TITLE
Create a function to trim constants from the PBT mutations dict

### ISSUE THREAD

**Issue by cooperlab** [PathologyDataScience/glimr#20]
Constant values that are not mutatable should be removed from the `hyperparameter_mutations` argument of `PopulationBasedTraining`.

`Traceback (most recent call last):
  File "i-score.py", line 59, in <module>
    attempt_tuning(
  File "/renal_allograft/code/utils/attempt_tuning.py", line 35, in attempt_tuning
    scheduler = PopulationBasedTraining(
  File "/usr/local/lib/python3.8/dist-packages/ray/tune/schedulers/pbt.py", line 360, in __init__
    raise TypeError(
TypeError: `hyperparam_mutation` values must be either a List, Tuple, Dict, a tune search space object, or a callable.`

**Comment by cooperlab** [comment]
`hyperparameter_mutations` is a nested dict and top-level constants will trigger this error.

Nested constants will pass this check: [https://github.com/ray-project/ray/blob/8427de2776717b30086c277e5e8e140316dbd193/python/ray/tune/schedulers/pbt.py#L360](https://github.com/ray-project/ray/blob/8427de2776717b30086c277e5e8e140316dbd193/python/ray/tune/schedulers/pbt.py#L360). Need to determine if they will trigger subsequent errors and need to be trimmed.

**Comment by cooperlab** [comment]
Recurse into dicts and locate and remove constant values. We will need a list of types that qualify (it might be easier to rule-in than to rule-out).
